### ISSUE TITLE
Visualization demo code fails with version 1.5.0

### ISSUE THREAD

**Issue by MarkusKramer** [haifengl/smile#252]
I'm using a fresh installation of smile 1.5.0
The demo code posted here
https://haifengl.github.io/smile/visualization.html

    val iris = read.arff("data/weka/iris.arff", 4)
    val (x, y) = iris.unzipInt
    val x2 = x.map(_.slice(0,2)) // take first two columns

fails with

```
smile> val x2 = x.map(_.slice(0,2)) 
cmd2.sc:1: type mismatch;
 found   : x$1.type (with underlying type Array[Double])
 required: ?{def slice(x$1: ? >: Int(0),x$2: ? >: Int(2)): ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method doubleArrayOps in object Predef of type (xs: Array[Double])scala.collection.mutable.ArrayOps.ofDouble
 and method array2VectorExpression in trait Operators of type (x: Array[Double])smile.math.VectorLift
 are possible conversion functions from x$1.type to ?{def slice(x$1: ? >: Int(0),x$2: ? >: Int(2)): ?}
val x2 = x.map(_.slice(0,2))
               ^
cmd2.sc:1: value slice is not a member of Array[Double]
val x2 = x.map(_.slice(0,2))
                 ^
Compilation Failed

```

It's working in smile 1.4.0.

## Information

- What Java (OpenJDK, Orack JDK, etc.) are you using and which Java version
openjdk 8
- Which Smile version
1.5.0
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Linux Mint 18

**Comment by haifengl** [comment]
There is ambiguous implicit conversion. Both our API and Scala's Predef convert Array implicitly. Let me think of a way to avoid the conflicts while maintaining the functionality.

**Comment by haifengl** [comment]
I removed Traversable trait from our VectorExpression, which resolves this conflicts. However, you will have to call toArray first on our scala vector expression first to use map and other traversal functions.
