### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by rayeaster** [haifengl/smile#452]
![image](https://user-images.githubusercontent.com/1487283/62773855-db351400-bad5-11e9-8565-f732b1ba98ec.png)

@tdunning  seems introduced by https://github.com/haifengl/smile/pull/447

**Comment by haifengl** [comment]
Thanks. I fixed it.
